<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>24.02.00</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Common\src\Common.Structure\Common.Structure.csproj" />
    <ProjectReference Include="..\..\Common\src\Common.ReportWriting\Common.ReportWriting.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Nager.Date" />
    <PackageReference Include="System.Collections.Concurrent" />
    <PackageReference Include="System.IO.Abstractions" />
  </ItemGroup>
</Project>