<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>24.02.00</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Common\src\Common.Structure\Common.Structure.csproj" />
    <ProjectReference Include="..\..\Common\src\Common.ReportWriting\Common.ReportWriting.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Nager.Date" Version="[1.33.1]" />
    <PackageReference Include="System.Collections.Concurrent" Version="4.3.0" />
    <PackageReference Include="System.IO.Abstractions" Version="22.0.12" />
  </ItemGroup>
</Project>