<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <PropertyGroup>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>full</TrimMode>
    <SuppressTrimAnalysisWarnings>false</SuppressTrimAnalysisWarnings>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
    <TrimmerRemoveSymbols>true</TrimmerRemoveSymbols>
  </PropertyGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>$(AssemblyName).Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\src\Common.Console\Common.Console.csproj" />
    <ProjectReference Include="..\..\Common\src\Common.Structure\Common.Structure.csproj" />
    <ProjectReference Include="..\FinancialStructures\FinancialStructures.csproj" />
    <ProjectReference Include="..\FinancialStructures.Stocks\FinancialStructures.Stocks.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\test\FinancialStructures.Stocks.Tests\ExampleConfigFiles\Exchanges.csv" Link="ExampleConfigFiles\Exchanges.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <None Update="appsettings.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
