<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Abstractions.TestingHelpers" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\FinancialStructures\FinancialStructures.csproj" />
    <ProjectReference Include="..\..\Common\src\Common.Structure\Common.Structure.csproj" />
  </ItemGroup>
</Project>
